export const CHANGE_CHANNEL = 'CHANGE_CHANNEL';
export const GET_CHANNELS = 'GET_CHANNELS';
export const GET_CHANNEL_MESSAGES_REQUEST = 'GET_CHANNEL_MESSAGES_REQUEST';
export const GET_CHANNEL_MESSAGES_SUCCESS = 'GET_CHANNEL_MESSAGES_SUCCESS';
export const RESEIVE_MESSAGE = 'RESEIVE_MESSAGE';
