export const CHANGE_CHANNEL = 'CHANGE_CHANNEL';
export const GET_CHANNELS = 'GET_CHANNELS';
export const GET_CHANNEL_MESSAGES = 'GET_CHANNEL_MESSAGES';
export const RESEIVE_MESSAGE = 'RESEIVE_MESSAGE';